start_ext_vec = .;
*(.ext_vec_0)
. = start_ext_vec + 4;
*(.ext_vec_1)
. = start_ext_vec + 8;
*(.ext_vec_2)
. = start_ext_vec + 12;
*(.ext_vec_3)
. = start_ext_vec + 16;
*(.ext_vec_4)
. = start_ext_vec + 20;
*(.ext_vec_5)
. = start_ext_vec + 24;
*(.ext_vec_6)
. = start_ext_vec + 28;
*(.ext_vec_7)
. = start_ext_vec + 32;
*(.ext_vec_8)
. = start_ext_vec + 36;
*(.ext_vec_9)
. = start_ext_vec + 40;
*(.ext_vec_10)
. = start_ext_vec + 44;
*(.ext_vec_11)
. = start_ext_vec + 48;
*(.ext_vec_12)
. = start_ext_vec + 52;
*(.ext_vec_13)
. = start_ext_vec + 56;
*(.ext_vec_14)
. = start_ext_vec + 60;
*(.ext_vec_15)
. = start_ext_vec + 64;
*(.ext_vec_16)
. = start_ext_vec + 68;
*(.ext_vec_17)
. = start_ext_vec + 72;
*(.ext_vec_18)
. = start_ext_vec + 76;
*(.ext_vec_19)
. = start_ext_vec + 80;
*(.ext_vec_20)
. = start_ext_vec + 84;
*(.ext_vec_21)
. = start_ext_vec + 88;
*(.ext_vec_22)
. = start_ext_vec + 92;
*(.ext_vec_23)
. = start_ext_vec + 96;
*(.ext_vec_24)
. = start_ext_vec + 100;
*(.ext_vec_25)
. = start_ext_vec + 104;
*(.ext_vec_26)
. = start_ext_vec + 108;
*(.ext_vec_27)
. = start_ext_vec + 112;
*(.ext_vec_28)
. = start_ext_vec + 116;
*(.ext_vec_29)
. = start_ext_vec + 120;
*(.ext_vec_30)
. = start_ext_vec + 124;
*(.ext_vec_31)
. = start_ext_vec + 128;
*(.ext_vec_32)
. = start_ext_vec + 132;
*(.ext_vec_33)
. = start_ext_vec + 136;
*(.ext_vec_34)
. = start_ext_vec + 140;
*(.ext_vec_35)
. = start_ext_vec + 144;
*(.ext_vec_36)
. = start_ext_vec + 148;
*(.ext_vec_37)
. = start_ext_vec + 152;
*(.ext_vec_38)
. = start_ext_vec + 156;
*(.ext_vec_39)
. = start_ext_vec + 160;
*(.ext_vec_40)
. = start_ext_vec + 164;
*(.ext_vec_41)
. = start_ext_vec + 168;
*(.ext_vec_42)
. = start_ext_vec + 172;
*(.ext_vec_43)
. = start_ext_vec + 176;
*(.ext_vec_44)
. = start_ext_vec + 180;
*(.ext_vec_45)
. = start_ext_vec + 184;
*(.ext_vec_46)
. = start_ext_vec + 188;
*(.ext_vec_47)
. = start_ext_vec + 192;
*(.ext_vec_48)
. = start_ext_vec + 196;
*(.ext_vec_49)
. = start_ext_vec + 200;
*(.ext_vec_50)
. = start_ext_vec + 204;
*(.ext_vec_51)
. = start_ext_vec + 208;
*(.ext_vec_52)
. = start_ext_vec + 212;
*(.ext_vec_53)
. = start_ext_vec + 216;
*(.ext_vec_54)
. = start_ext_vec + 220;
*(.ext_vec_55)
. = start_ext_vec + 224;
*(.ext_vec_56)
. = start_ext_vec + 228;
*(.ext_vec_57)
. = start_ext_vec + 232;
*(.ext_vec_58)
. = start_ext_vec + 236;
*(.ext_vec_59)
. = start_ext_vec + 240;
*(.ext_vec_60)
. = start_ext_vec + 244;
*(.ext_vec_61)
. = start_ext_vec + 248;
*(.ext_vec_62)
. = start_ext_vec + 252;
*(.ext_vec_63)
. = start_ext_vec + 256;
*(.ext_vec_64)
. = start_ext_vec + 260;
*(.ext_vec_65)
. = start_ext_vec + 264;
*(.ext_vec_66)
. = start_ext_vec + 268;
*(.ext_vec_67)
. = start_ext_vec + 272;
*(.ext_vec_68)
. = start_ext_vec + 276;
*(.ext_vec_69)
. = start_ext_vec + 280;
*(.ext_vec_70)
. = start_ext_vec + 284;
*(.ext_vec_71)
. = start_ext_vec + 288;
*(.ext_vec_72)
. = start_ext_vec + 292;
*(.ext_vec_73)
. = start_ext_vec + 296;
*(.ext_vec_74)
. = start_ext_vec + 300;
*(.ext_vec_75)
. = start_ext_vec + 304;
*(.ext_vec_76)
. = start_ext_vec + 308;
*(.ext_vec_77)
. = start_ext_vec + 312;
*(.ext_vec_78)
. = start_ext_vec + 316;
*(.ext_vec_79)
. = start_ext_vec + 320;
*(.ext_vec_80)
. = start_ext_vec + 324;
*(.ext_vec_81)
. = start_ext_vec + 328;
*(.ext_vec_82)
. = start_ext_vec + 332;
*(.ext_vec_83)
. = start_ext_vec + 336;
*(.ext_vec_84)
. = start_ext_vec + 340;
